-- Crear la tabla de clientes
CREATE TABLE public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- Un cliente con el mismo nombre y teléfono para el mismo usuario debe ser único
    CONSTRAINT unique_customer_for_user UNIQUE (user_id, name, phone)
);

-- Comentario para la tabla
COMMENT ON TABLE public.clientes IS 'Tabla para almacenar los clientes de cada usuario del sistema.';

-- Modificar la tabla de pedidos para añadir la relación con clientes
ALTER TABLE public.pedidos
ADD COLUMN cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE SET NULL;

-- Opcional: Añadir un índice para búsquedas rápidas
CREATE INDEX idx_clientes_user_id ON public.clientes (user_id);
CREATE INDEX idx_pedidos_cliente_id ON public.pedidos (cliente_id);
