CREATE TABLE public.tiendas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    "storeName" text,
    description text,
    "buyText" text,
    cards jsonb,
    faqs jsonb,
    colors jsonb,
    "logoUrl" text,
    "mainUrl" text,
    "galleryUrls" jsonb,
    "videoUrl" text,
    variants jsonb,
    whatsapp jsonb,
    emails jsonb,
    addresses jsonb,
    animation jsonb,
    sections jsonb
);
ALTER TABLE public.tiendas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON public.tiendas FOR SELECT USING (true);
CREATE POLICY "Allow anon insert" ON public.tiendas FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update" ON public.tiendas FOR UPDATE USING (true) WITH CHECK (true);
