// scripts/migrations/002_add_riel_plan.js
require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });
const { supabaseAdmin } = require('../../backend/services/supabase');

const MIGRATION_NAME = '002_add_riel_plan';

async function runMigration() {
  console.log(`--- Iniciando migración: ${MIGRATION_NAME} ---`);

  try {
    // Paso 1: Crear la tabla para pre-registros de Riel
    console.log("1. Creando tabla 'riel_preregistrations'...");
    const createTableSql = `
      CREATE TABLE IF NOT EXISTS public.riel_preregistrations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        identifier UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
        whatsapp_number TEXT NOT NULL,
        status TEXT DEFAULT 'pending' NOT NULL, -- pending, claimed
        created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
        claimed_at TIMESTAMPTZ,
        user_uuid UUID
      );
      COMMENT ON TABLE public.riel_preregistrations IS 'Almacena solicitudes para cuentas gratuitas de Riel antes de la creación del usuario.';
    `;
    const { error: tableError } = await supabaseAdmin.rpc('execute_sql', { sql: createTableSql });
    if (tableError) throw tableError;
    console.log("   ... Tabla 'riel_preregistrations' creada o ya existente.");

    // Paso 2: Insertar o actualizar el plan 'Riel' en la tabla 'planes'
    console.log("2. Insertando o actualizando el plan 'riel' en la tabla 'planes'...");
    const { error: upsertError } = await supabaseAdmin
      .from('planes')
      .upsert({
        nombre: 'riel',
        precio: 0,
        duracion_meses: 1,
        product_limit: 15
      }, {
        onConflict: 'nombre'
      });
      
    if (upsertError) {
        throw upsertError;
    }
    console.log("   - Plan 'riel' con límite de 15 productos asegurado en la base de datos.");

    console.log(`\n--- Migración ${MIGRATION_NAME} completada con éxito. ---`);

  } catch (error) {
    console.error(`\n[ERROR FATAL] Falló la migración ${MIGRATION_NAME}:`, error.message);
    process.exit(1);
  }
}

runMigration();
