-- MIGRATION SCRIPT 006
-- Creates tables for Riel store analytics.

BEGIN;

-- Tabla para registrar las visitas a las tiendas
CREATE TABLE IF NOT EXISTS public.store_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    session_id UUID NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_store_visits_store_id ON public.store_visits(store_id);
COMMENT ON TABLE public.store_visits IS 'Records each visit to a Riel store for analytics.';

-- Tabla para registrar las interacciones con los productos
CREATE TABLE IF NOT EXISTS public.product_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    product_id_local TEXT NOT NULL,
    interaction_type TEXT NOT NULL, -- 'like', 'nope', 'add_to_cart'
    session_id UUID NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_product_interactions_store_id_product_id ON public.product_interactions(store_id, product_id_local);
COMMENT ON TABLE public.product_interactions IS 'Records user interactions (swipes) with products in Riel stores.';

-- Habilitar Row Level Security
ALTER TABLE public.store_visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_interactions ENABLE ROW LEVEL SECURITY;

-- Políticas de seguridad: Permitir inserción pública, pero la lectura y modificación solo al dueño.
-- Cualquiera puede registrar una visita o una interacción.
CREATE POLICY "Public can insert visits and interactions" ON public.store_visits FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can insert product interactions" ON public.product_interactions FOR INSERT WITH CHECK (true);

-- El dueño de la tienda puede leer las interacciones y visitas de su propia tienda.
CREATE POLICY "Store owner can read their own stats" ON public.store_visits FOR SELECT
    USING (store_id IN (
        SELECT id FROM public.stores WHERE usuario_id = (SELECT id FROM public.usuarios WHERE uuid = auth.uid())
    ));

CREATE POLICY "Store owner can read their own product interactions" ON public.product_interactions FOR SELECT
    USING (store_id IN (
        SELECT id FROM public.stores WHERE usuario_id = (SELECT id FROM public.usuarios WHERE uuid = auth.uid())
    ));

COMMIT;

-- END OF MIGRATION SCRIPT 006
