-- 1) Crear tabla stores (estructura completa y segura)
CREATE TABLE IF NOT EXISTS public.stores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT UNIQUE NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  descripcion TEXT,
  logo_url TEXT,
  direccion TEXT,
  telefono VARCHAR(50),
  activa BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT fk_usuario
    FOREIGN KEY(usuario_id)
    REFERENCES public.usuarios(id)
    ON DELETE CASCADE
);

COMMENT ON TABLE public.stores IS 'Almacena la información de las tiendas de los usuarios.';
COMMENT ON COLUMN public.stores.usuario_id IS 'ID del usuario propietario de la tienda. Debe ser único.';

-- 2) Insertar una tienda de prueba para usuario_id = 17 (ajusta nombre/desc si quieres)
INSERT INTO public.stores (usuario_id, nombre, descripcion)
VALUES (17, 'Mi Tienda de Prueba', 'Esta es una tienda de demostración para el usuario 17.')
RETURNING id;

-- 3) Verificar contenido insertado
SELECT * FROM public.stores WHERE usuario_id = 17;
